name: Pre-production workflow

on:
  push:
    branches:
      - pre
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run : npm install
      - run: npm run build:pre
