name: Pre-production workflow

on:
  push:
    branches:
      - pre
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run : npm install
      - run: npm run test
        if: success()
      - run: npm run build:pre
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.PRE_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PRE_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist/gameofchars-front --prod
          secrets: '["PRE_NETLIFY_AUTH_TOKEN", "PRE_NETLIFY_SITE_ID"]'
